{% set name = "py-partiql-parser" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py_partiql_parser-{{ version }}.tar.gz
  sha256: 72e043919538fa63edae72fb59afc7e3fd93adbde656718a7d2b4666f23dd114

build:
  skip: true # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python

test:
  imports:
    - py_partiql_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/getmoto/py-partiql-parser/
  summary: Pure Python PartiQL Parser
  description: |
    A tokenizer/parser/executor for the PartiQL-language, in Python.
  dev_url: https://github.com/getmoto/py-partiql-parser/
  doc_url: https://github.com/getmoto/py-partiql-parser/
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JamesRobertsonGames
